# -*- coding: utf-8 -*-
"""WebScarpinngGettingProxies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/199iEGkXryjk8pXD4N9o33BAMtwBv84Nj
"""

import requests
import random
from bs4 import BeautifulSoup as bs4
import traceback

pr = "https://free-proxy-list.net"
def get_free_proxies(url):
  #geting the content with BS4
  soup = bs4(requests.get(pr).content, 'html.parser')

  #storing the proxies
  proxies = []

  for i in soup.find("div",attrs={'class': "table-responsive fpl-list"}).find_all("tr")[1:]:
      tds = i.find_all("td")

      try:
        ip = tds[0].text.strip()
        port = tds[1].text.strip()
        proxies.append(str(ip)  + ":" + str(port))
      except IndexError:
        continue

  return proxies

proxies = get_free_proxies(pr)

url = "http://httpbin.org/ip"

for i in range(len(proxies)):
  print("request number: ", i+1)

  proxy = proxies[i]

  try:
    response = requests.get(url, proxies = {"http":proxy, "https":proxy})
    print(response.json())
  except:
    print("Indisponivel")
  break

